---
-
  hosts: all
  tasks:
    - name: Command delegation to other server1
      command:
        "ifconfig -a" 
      delegate_to: server1
      register: delegate_server1
      tags: delegate_1

    - name: to display delagate server1 output
      debug:
        var: delegate_server1
      tags: delegate_2  

    - name: restart ssh service on delegate server2
      service:
        name: ssh
        state: restarted
      delegate_to: server2
      run_once: true
      tags: delegate_3  
