---
-
  hosts: all
  tasks:
    - name: setfact 
      set_fact:
        our_fact: Ansible Rocks.
        ansible_distribution: "{{ ansible_distribution }}"

    - name: shows default facts    
      debug:
        msg: "{{ ansible_distribution }}"  
        
    - name: shows custom fact
      debug:
        msg: "{{ our_fact }}"



