---
-
  hosts: all
  tasks:
    - name: archive a folder
      archive:
        path: /tmp/Hello
        dest: /tmp/Hello.tar
        format: tar       
      tags: archive_folder_tar  

    - name: list  archieve registered to var
      ansible.builtin.command: ls -lrt /tmp/Hello.tar
      register: folder_archive_tar_stats    
    - debug: var=folder_archive_tar_stats.stdout_lines       
